name: Build and Test

on:
  push:
    branches:
      - main
      - test-branch-name
    pull_request:
      types:
        - opened
        - synchronize
        - reopened
      branches:
        - "**"

permissions:
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          git switch naza ${{ github.head_ref }}
